package GSILabs.ProyectoFinal.Propietario;

import GSILabs.BModel.Usuario;

/**
 * Clase DetallesDonacion
 * Interfaz Gráfica mediante la que se muestran los detalles
 * de una donación seleccionada en la interfaz gráfica MenuHistorialDonaciones.
 * @author Grupo 3 - GSI
 * @version 1.0
 * @since 02.12.2023
 */
public class DetallesDonacion extends javax.swing.JFrame {
    
    /**
     * Usuario mediante el que se está ejecutando el programa.
     */
    private Usuario usuario = null;

    /**
     * Constructor DetallesDonacion
     * @param usuario Usuario con la que se está utilizando la aplicación.
     */
    public DetallesDonacion(Usuario usuario){
        initComponents();
        this.textoCantidad.setEditable(false);
        this.textoComida.setEditable(false);
        this.textoLocal.setEditable(false);
        this.usuario = usuario;
        
        super.setVisible(true);
        super.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form DetallesDonacion
     * @param cantidad
     * @param comida
     * @param local
     */
    public DetallesDonacion(String comida, String cantidad, String local) {
        initComponents();
        this.textoCantidad.setEditable(false);
        this.textoComida.setEditable(false);
        this.textoLocal.setEditable(false);
        this.textoCantidad.setEditable(false);
        this.textoCantidad.setText(cantidad);
        this.textoComida.setText(comida);
        this.textoLocal.setText(local);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDonacion = new javax.swing.JLabel();
        labelComida = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelLocal = new javax.swing.JLabel();
        //labelFecha = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        textoComida = new javax.swing.JTextField();
        textoCantidad = new javax.swing.JTextField();
        textoLocal = new javax.swing.JTextField();
        //textoFecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDonacion.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        labelDonacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDonacion.setText("Donacion");

        labelComida.setText("Comida:");

        labelCantidad.setText("Cantidad:");

        labelLocal.setText("Local:");

        //labelFecha.setText("Fecha:");

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        textoCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCantidadActionPerformed(evt);
            }
        });

        textoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoLocalActionPerformed(evt);
            }
        });
/*
        textoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFechaActionPerformed(evt);
            }
        });
*/
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(labelDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
       /*                     .addComponent(labelFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        */                    .addComponent(labelLocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelComida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVolver)
                            .addComponent(textoComida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
       /*                     .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        */                    .addComponent(textoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDonacion)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComida)
                    .addComponent(textoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidad)
                    .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocal)
                    .addComponent(textoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
       /*         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
       */         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void textoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCantidadActionPerformed

    private void textoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoLocalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelComida;
    private javax.swing.JLabel labelDonacion;
    private javax.swing.JLabel labelLocal;
    private javax.swing.JTextField textoCantidad;
    private javax.swing.JTextField textoComida;
    private javax.swing.JTextField textoLocal;
    // End of variables declaration//GEN-END:variables
}
