package GSILabs.ProyectoFinal.Propietario;

import GSILabs.BModel.Donacion;
import GSILabs.BModel.Local;
import GSILabs.BModel.Usuario;
import static GSILabs.MongoDB.ConexionBBDD.cargarDonacion;

/**
 * Clase MenuDonacion
 * Interfaz Gráfica mediante la que se realizan las donaciones
 * por parte del usuario introduciendo la descripción de la comida
 * que se va a donar y las unidades.
 * @author Grupo 3 - GSI
 * @version 1.0
 * @since 02.12.2023
 */
public class MenuDonacion extends javax.swing.JFrame {
    
    /**
     * Usuario mediante el que se está ejecutando el programa.
     */
    private Usuario usuario = null;
    private Local local = null;

    /**
     * Constructor MenuDonacion
     * @param usuario Usuario con la que se está utilizando la aplicación.
     * @param local local con el que se esta utilizando la aplicacion
     */
    public MenuDonacion(Usuario usuario, Local local) {
        initComponents();
        this.usuario = usuario;
        this.local = local;
        
        super.setVisible(true);
        super.setLocationRelativeTo(null);
    }

    MenuDonacion(MenuPropietario aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDonacion = new javax.swing.JLabel();
        labelComida = new javax.swing.JLabel();
        textFieldComida = new javax.swing.JTextField();
        labelUnidades = new javax.swing.JLabel();
        spinnerUnidades = new javax.swing.JSpinner();
        botonDonar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDonacion.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        labelDonacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDonacion.setText("Donación");

        labelComida.setText("Comida:");

        textFieldComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldComidaActionPerformed(evt);
            }
        });

        labelUnidades.setText("Unidades:");

        botonDonar.setText("Donar");
        botonDonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDonarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(labelDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textFieldComida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelComida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUnidades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerUnidades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(botonDonar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDonacion)
                .addGap(18, 18, 18)
                .addComponent(labelComida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUnidades)
                .addGap(13, 13, 13)
                .addComponent(spinnerUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDonar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldComidaActionPerformed

    private void botonDonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDonarActionPerformed
        String comida = this.textFieldComida.getText();
        int numComida = (int)this.spinnerUnidades.getValue();
        System.out.println(comida + ": " + numComida);
        //añadirComida(listaComida, comida, numComida); habria que crear una funcion que hiciera algo asi conectando a la BBDD
        
        // Donacion
        Donacion donacion = new Donacion(local, comida, numComida);
        cargarDonacion(donacion);
        
        this.dispose();
    }//GEN-LAST:event_botonDonarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDonar;
    private javax.swing.JLabel labelComida;
    private javax.swing.JLabel labelDonacion;
    private javax.swing.JLabel labelUnidades;
    private javax.swing.JSpinner spinnerUnidades;
    private javax.swing.JTextField textFieldComida;
    // End of variables declaration//GEN-END:variables
}
