package GSILabs.ProyectoFinal.Login;

import GSILabs.BModel.Bar;
import GSILabs.BModel.Direccion;
import GSILabs.BModel.Local;
import GSILabs.BModel.Propietario;
import GSILabs.BModel.Pub;
import GSILabs.BModel.Restaurante;
import GSILabs.BSystem.BusinessSystem;
import static GSILabs.MongoDB.ConexionBBDD.CargarDatos;
import static GSILabs.MongoDB.ConexionBBDD.DescargarDatos;
import GSILabs.ProyectoFinal.Propietario.MenuPropietario;
import javax.swing.JOptionPane;

/**
 * Clase EspecificacionesLocal
 * Interfaz gráfica con la que un propietario que se está registrando introduce
 * los datos de su local.
 * @author Grupo 3 - GSI
 * @version 1.0
 * @since 05.12.2023
 */
public class EspecificacionesLocal extends javax.swing.JFrame {
    
    /**
     * Almacena datos del usuario que está utilizando la aplicación.
     */
    private Propietario propietario = null;

    /**
     * Constructor EspecificacionesLocal.
     * @param propietario Propietario del local del cual se introducen los datos.
     */
    public EspecificacionesLocal(Propietario propietario) {
        initComponents();
        this.propietario = propietario;
        
        super.setVisible(true);
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cBoxTipoLocal = new javax.swing.JComboBox<>();
        botonVolver = new javax.swing.JButton();
        botonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Especificaciones Local");

        jLabel2.setText("Nombre del local");

        jLabel3.setText("Dirección del local");

        jLabel4.setText("Descripción");

        jLabel5.setText("Tipo local");

        cBoxTipoLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurante", "Bar", "Pub" }));
        cBoxTipoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxTipoLocalActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonConfirmar.setText("Confirmar");
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldNombre)
                            .addComponent(fieldDireccion)
                            .addComponent(fieldDescripcion)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(cBoxTipoLocal, 0, 479, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBoxTipoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Creo que no es necesario hacerlo aquí, habría que hacerlo al pulsar el botón confirmar.
    private void cBoxTipoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxTipoLocalActionPerformed
        //Hacer insert a la Base de Datos
        //Pasar vista a menu Propiertario
    }//GEN-LAST:event_cBoxTipoLocalActionPerformed

    /**
     * Función ActionPerformed para el JButton botonVolver, mediante la que se
     * vuelve a la ventana de introducción de datos del propietario.
     * @param evt Evento recibido por la función
     */
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        RegistrarUsuario abrirRegistrarUsuario = new RegistrarUsuario();
        abrirRegistrarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed

    /**
     * Función ActionPerformed para el boton botonConfirmar en la que en primer
     * lugar comprobamos si todos los campos están rellenados;
     * En caso contrario se muestra un JOptionPane de error;
     * Si se han introducido correctamente los datos entonces se crea el nuevo
     * perfil de propietario con las especificaciones de local y se le redirige
     * a la ventana MenuPropietario.
     * @param evt Evento recibido por la función
     */
    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        if(fieldNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor, introduzca un nombre al local.");
        } else if(fieldDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor, introduzca una direccion al local.");
        } else if(fieldDescripcion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Porfavor, introduzca una descripcion al local.");
        } else {
            //Rellenamos atributos para clase Local
            String nombreLocal = this.fieldNombre.getText();
            Direccion direccion = null;
            String descripcion = this.fieldDescripcion.getText();
            
            BusinessSystem bs = DescargarDatos();
            
            //Local local = null;
            if((cBoxTipoLocal.getItemAt(cBoxTipoLocal.getSelectedIndex())).equals("Bar")) {
                //tipo = tipoLocal.BAR;
                System.out.println("AAAAAAA");
                Bar local = new Bar(nombreLocal, direccion, descripcion, this.propietario);
                this.propietario.setLocal(local);
                if (bs.obtenerLocal(local.getDireccion()) != null) {
                    System.out.println("Este local ya existe");
                } else {
                    bs.nuevoLocal(local);
                    bs.asociarLocal(local, this.propietario);

                    System.out.println("Este local no existe");
                    CargarDatos(bs);            
                }
            } else if((cBoxTipoLocal.getItemAt(cBoxTipoLocal.getSelectedIndex())).equals("Restaurante")) {
                //tipo = tipoLocal.RESTAURANTE;
                Restaurante local = new Restaurante(nombreLocal, direccion, descripcion, this.propietario, 12.0, null, null);
            } else if((cBoxTipoLocal.getItemAt(cBoxTipoLocal.getSelectedIndex())).equals("Pub")) {
                //tipo = tipoLocal.PUB;
                Pub local = new Pub(null, null, nombreLocal, direccion, descripcion, this.propietario);
            }
            
            /*BusinessSystem bs = DescargarDatos();
            this.propietario.setLocal(local);

            if (bs.obtenerLocal(local.getDireccion()) != null) {
                System.out.println("Este local ya existe");
            } else {
                bs.nuevoLocal(local);
                bs.asociarLocal(local, this.propietario);
                
                System.out.println("Este local no existe");
                CargarDatos(bs);            
            }*/
            
            MenuPropietario abrirMenuPropietario = new MenuPropietario(propietario);
            this.setVisible(false);
        }
            
        System.out.println("Nombre" + fieldNombre.getText());
        System.out.println("Direccion" + fieldDireccion.getText());
        System.out.println("Descripcion" + fieldDescripcion.getText());
        System.out.println("Tipo" + cBoxTipoLocal.getItemAt(cBoxTipoLocal.getSelectedIndex()));
    }//GEN-LAST:event_botonConfirmarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> cBoxTipoLocal;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
